### PR TITLE
edgeTransport 2.0 release

### PR DESCRIPTION
**Pull request by johannah-pik**
mrtransport is a madrat input data package for transport standalone input data
and is used by edgeTransport 2.0

### CODE REVIEW

**Review by LaviniaBaumstark — COMMENTED** [review]
why did you rebuild it? There are no file changes, right?

**Comment by fbenke-pik** [comment]
> why did you rebuild it? There are no file changes, right?

To increment from a development version number to a non-development version number

**Comment by johannah-pik** [comment]
Just to move away from the development package number

**Comment by LaviniaBaumstark** [comment]
ah, thanks

**Review by LaviniaBaumstark — APPROVED** [review]

**Review by jmuessel — APPROVED** [review]

**Pull request merged**
